---
functional:
  - Пользователь должен иметь возможность зарегистрироваться с помощью электронной почты
  - Пользователь должен иметь возможность авторизоваться на сайте с помощью электронной почты
  - Пользователь должен иметь возможность авторизоваться на сайте с помощью электронной Github
  - Пользователь должен иметь возможность авторизоваться на сайте с помощью электронной Discord
  - Пользователь должен иметь возможность найти друга по "никнейму" среди зарегестрированных пользователей
  - Пользователь должен иметь возможность создать игру с другом
  - Пользователь должен иметь возможность создать турнир
  - Пользователь должен иметь возможность зайти в созданный турнир как зритель
  - Пользователь должен иметь возможность просматривать профили других игроков
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен поддерживать устройства, работающие на операционных системах IOS 9.0- 17.0 и Android 7.0 – 14.0
  - Сайт должен работать стабильно в период пиковой нагрузки
implicit:
  - Пользователь имеет возможность написать личное сообщение другу
  - Пользователь не может использовать запрещенные символы в имени пользователя
  - Пользователь должен иметь возможность выбирать в какой игре принимать участие
  - Пользователь должен иметь возможность выбрать язык локализации
  - У пользователя должна быть возможность изменять свой пароль
  - В разделе "My Profile" должна быть возможность добавления фотографии пользователя
  - В разделе "Settings" должна быть возможность изменения имени пользователя
  - В разделе "Settings" должна быть возможность выбора языка программирования для участия в батлах
  - В разделе "Settings" должна быть возможность выбора звукового сопровождения по завершению матча
  - В разделе "Settings" должна быть возможность регулировка громкости звукового сопровождения по завершению матча
  - Сайт должен иметь возможность выбора тёмной темы
  
